id: pato
title: "Phenotype And Trait Ontology"
github_org: pato-ontology
repo: pato
report_fail_on: none
edit_format: obo
export_formats:
  - owl
  - obo
  - json
release_artefacts: 
  - base
  - simple
  - full
primary_release: full
import_group:
  products:
    - id: ro
    - id: chebi
      mirror_from: http://purl.obolibrary.org/obo/chebi.owl.gz
    - id: go
    - id: pco
    - id: uberon
components:
  products:
    - filename: pato_ext.owl
robot_java_args: '-Xmx8G'