id: pato
title: "Phenotype And Trait Ontology"
github_org: pato-ontology
repo: pato
report_fail_on: none
export_formats:
  - owl
  - obo
  - json
release_artefacts: 
  - base
  - simple
  - full
primary_release: simple
import_group:
  products:
    - id: ro
    - id: chebi
    - id: go
    - id: pco
    - id: uberon
robot_java_args: '-Xmx8G'